DEVICE     = atmega328p
CLOCK      = 16000000
OBJECTS    = src/main.o src/enc28j60.o src/light_ws2812.o src/ws2812.o src/spi.o src/ethernet_protocols.o src/cos_approx.o
LIBS       = 
LIBDIR     = 
LIBINCLUDE = 
FUSES      = -U lfuse:w:0xfe:m -U hfuse:w:0xd9:m -U efuse:w:0xff:m
# generated by http://www.engbedded.com/fusecalc/

AVRDUDE = avrdude -C/usr/share/arduino/hardware/tools/avrdude.conf -q -q -cstk500v1 -pm328p -P/dev/ttyUSB0 -b57600 -D
COMPILE = avr-gcc -Os -DF_CPU=$(CLOCK) -mmcu=$(DEVICE)

all:	main.hex memory-used

%.o:	%.c
	$(COMPILE) -c $< -o $@ $(LIBINCLUDE)

flash:	all
	sudo python -c 'import sys, serial, time; ser = serial.Serial(sys.argv[1], 57600); ser.setDTR(0); time.sleep(0.1); ser.setDTR(1); ser.close()' /dev/ttyUSB0
	sudo $(AVRDUDE) -U flash:w:src/main.hex

clean:
	rm -f src/main.hex src/main.elf $(OBJECTS)

main.elf: $(OBJECTS)
	$(COMPILE) -o src/main.elf $(OBJECTS) -static $(LIBDIR) $(LIBS)

main.hex: main.elf
	rm -f src/main.hex
	avr-objcopy -j .text -j .data -O ihex src/main.elf src/main.hex

disasm:	main.elf
	avr-objdump -D src/main.elf

memory-used: main.elf
	avr-size --mcu=$(DEVICE) -C src/main.elf
