DEVICE     = atmega328p
CLOCK      = 16000000
OBJECTS    = main.o enc28j60.o light_ws2812.o ws2812.o spi.o ethernet_protocols.o cos_approx.o
LIBS       = 
LIBDIR     = 
LIBINCLUDE = 
FUSES      = -U lfuse:w:0xfe:m -U hfuse:w:0xd9:m -U efuse:w:0xff:m
# generated by http://www.engbedded.com/fusecalc/

AVRDUDE = avrdude -C/usr/share/arduino/hardware/tools/avrdude.conf -q -q -cstk500v1 -pm328p -P/dev/ttyUSB0 -b57600 -D
COMPILE = avr-gcc -Os -DF_CPU=$(CLOCK) -mmcu=$(DEVICE)

all:	main.hex memory-used

%.o:	%.c
	$(COMPILE) -c $< -o $@ $(LIBINCLUDE)

flash:	all
	python /home/marenz/programming/avr/arduino_scripts/arduino_reset.py /dev/ttyUSB0
	$(AVRDUDE) -U flash:w:main.hex

fuse:
	$(AVRDUDE) $(FUSES)

install: flash fuse

clean:
	rm -f main.hex main.elf $(OBJECTS)

main.elf: $(OBJECTS)
	$(COMPILE) -o main.elf $(OBJECTS) -static $(LIBDIR) $(LIBS)

main.hex: main.elf
	rm -f main.hex
	avr-objcopy -j .text -j .data -O ihex main.elf main.hex

disasm:	main.elf
	avr-objdump -D main.elf

memory-used: main.elf
	avr-size --mcu=$(DEVICE) -C main.elf
