DEVICE     = atmega328p
CLOCK      = 16000000
OBJECTS    = src/main.o src/light_ws2812.o src/spi.o src/cos_approx.o
VOBJECTS   = src/ethernet_protocols.o src/enc28j60.o src/ws2812.o
# generated by http://www.engbedded.com/fusecalc/
FUSES      = -U lfuse:w:0xfe:m -U hfuse:w:0xd9:m -U efuse:w:0xff:m

TARGETS = $(shell ls configs/*.h)
override _TARGETS = $(basename $(notdir $(TARGETS)))

FLASH = 

ifdef FLASH
override _FLASH = $(basename $(notdir $(FLASH)))
override _TARGETS = 
else
override _FLASH =
endif

AVRDUDE = avrdude -C/usr/share/arduino/hardware/tools/avrdude.conf -q -q -cstk500v1 -pm328p -P/dev/ttyUSB0 -b57600 -D
COMPILE = avr-gcc -Os -DF_CPU=$(CLOCK) -mmcu=$(DEVICE) -std=gnu99

PUR = \033[0;35m
NC = \033[0m

.PHONY: clean fuse

.PRECIOUS: %.elf

all:	$(addsuffix .hex, $(_TARGETS)) $(addsuffix .flash, $(_FLASH))

objects: $(OBJECTS)

%.o:	%.c
	$(COMPILE) -c $< -o $@

%.flash: %.hex
	sudo python -c 'import sys, serial, time; ser = serial.Serial(sys.argv[1], 57600); ser.setDTR(0); time.sleep(0.1); ser.setDTR(1); ser.close()' /dev/ttyUSB0
	sudo $(AVRDUDE) -U flash:w:$<

clean:
	rm -f $(addsuffix .hex, $(_TARGETS)) $(addsuffix .elf, $(_TARGETS)) $(OBJECTS)

%.elf: FORCE
	echo "$(PUR)Building objects$(NC)"
	make objects
	echo "$(PUR)Copying variable include file$(NC)"
	cp -f configs/$(basename $@).h src/config.h
	echo "$(PUR)Building objects files with variable includes$(NC)"
	make --always-make $(VOBJECTS)
	echo "$(PUR)Building $(basename $@) binary$(NC)"
	$(COMPILE) -o $@ $(OBJECTS) $(VOBJECTS)

%.hex: %.elf
	rm -f $@
	avr-objcopy -j .text -j .data -O ihex $(basename $@).elf $@
	echo "$(PUR)$(basename $@) binary$(NC)"
	avr-size $(basename $@).elf --mcu=$(DEVICE) --format=avr

FORCE:
